name: test4
version: '${project.version}'
main: me.unlegitiment.test4.Test4
api-version: 1.19
commands:
  testDEV:
    description: test
  test2:
    description: test2
  rank:
    description: Rank Changer File